// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	AddProductToCategory(ctx context.Context, arg AddProductToCategoryParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int64) (Category, error)
	DeleteProduct(ctx context.Context, id int64) (Product, error)
	FindCategoryById(ctx context.Context, id int64) (Category, error)
	FindProductById(ctx context.Context, id int64) (Product, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	IsTokenRevoked(ctx context.Context, jti string) (bool, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListOrdersByCustomerID(ctx context.Context, customerID int64) ([]ListOrdersByCustomerIDRow, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsByCategory(ctx context.Context, categoryID int64) ([]Product, error)
	RemoveProductFromCategory(ctx context.Context, arg RemoveProductFromCategoryParams) error
	RevokeToken(ctx context.Context, arg RevokeTokenParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
