// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id int64) (Product, error)
	FindProductById(ctx context.Context, id int64) (Product, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	IsTokenRevoked(ctx context.Context, jti string) (bool, error)
	ListProducts(ctx context.Context) ([]Product, error)
	RevokeToken(ctx context.Context, arg RevokeTokenParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
