// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	AddItemToCart(ctx context.Context, arg AddItemToCartParams) (CartItem, error)
	AddProductToCategory(ctx context.Context, arg AddProductToCategoryParams) error
	CancelOrder(ctx context.Context, id int64) (Order, error)
	ClearCart(ctx context.Context, userID int64) error
	ConsumeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateCart(ctx context.Context, userID int64) (Cart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int64) (Category, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteProduct(ctx context.Context, id int64) (Product, error)
	DeleteRefreshToken(ctx context.Context, id int64) error
	DeleteRefreshTokensByUserId(ctx context.Context, userID int64) error
	FindAddressByUserId(ctx context.Context, userID int64) (Address, error)
	FindCategoryById(ctx context.Context, id int64) (Category, error)
	FindOrderById(ctx context.Context, id int64) (FindOrderByIdRow, error)
	FindProductById(ctx context.Context, id int64) (Product, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserById(ctx context.Context, id int64) (User, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	IsTokenRevoked(ctx context.Context, jti string) (bool, error)
	ListAllOrders(ctx context.Context) ([]ListAllOrdersRow, error)
	ListCartItemsByUserId(ctx context.Context, userID int64) ([]ListCartItemsByUserIdRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListOrdersByCustomerID(ctx context.Context, customerID int64) ([]ListOrdersByCustomerIDRow, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsByCategory(ctx context.Context, categoryID int64) ([]Product, error)
	RemoveItemFromCart(ctx context.Context, id int64) (CartItem, error)
	RemoveProductFromCategory(ctx context.Context, arg RemoveProductFromCategoryParams) error
	RevokeToken(ctx context.Context, arg RevokeTokenParams) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
