// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addItemToCart = `-- name: AddItemToCart :one
INSERT INTO cart_items (cart_id, product_id, quantity) VALUES ($1, $2, $3) RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type AddItemToCartParams struct {
	CartID    int64 `json:"cart_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) AddItemToCart(ctx context.Context, arg AddItemToCartParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addItemToCart, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addProductToCategory = `-- name: AddProductToCategory :exec
INSERT INTO product_categories (product_id, category_id) VALUES ($1, $2)
`

type AddProductToCategoryParams struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) AddProductToCategory(ctx context.Context, arg AddProductToCategoryParams) error {
	_, err := q.db.Exec(ctx, addProductToCategory, arg.ProductID, arg.CategoryID)
	return err
}

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'cancelled', updated_at = now()
WHERE id = $1
RETURNING id, customer_id, created_at, status, updated_at
`

func (q *Queries) CancelOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = (SELECT id FROM carts WHERE user_id = $1)
`

func (q *Queries) ClearCart(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
DELETE FROM refresh_tokens
WHERE token_hash = $1 AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, created_at
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (user_id, street, city, state, zip_code, country) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, street, city, state, zip_code, country, created_at, updated_at
`

type CreateAddressParams struct {
	UserID  int64  `json:"user_id"`
	Street  string `json:"street"`
	City    string `json:"city"`
	State   string `json:"state"`
	ZipCode string `json:"zip_code"`
	Country string `json:"country"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Street,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Country,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id) VALUES ($1) RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, userID int64) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id) VALUES ($1) RETURNING id, customer_id, created_at, status, updated_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_in_cents)
VALUES ($1, $2, $3, $4) RETURNING id, order_id, product_id, quantity, price_in_cents
`

type CreateOrderItemParams struct {
	OrderID      int64 `json:"order_id"`
	ProductID    int64 `json:"product_id"`
	Quantity     int32 `json:"quantity"`
	PriceInCents int32 `json:"price_in_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceInCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceInCents,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price_in_cents) VALUES ($1, $2) RETURNING id, name, price_in_cents, quantity, created_at
`

type CreateProductParams struct {
	Name         string `json:"name"`
	PriceInCents int32  `json:"price_in_cents"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceInCents)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role) VALUES ($1, $2, $3, $4) RETURNING id, name, email, password_hash, created_at, role, updated_at
`

type CreateUserParams struct {
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, deleteCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products
WHERE id = $1
RETURNING id, name, price_in_cents, quantity, created_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, id)
	return err
}

const deleteRefreshTokensByUserId = `-- name: DeleteRefreshTokensByUserId :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserId(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserId, userID)
	return err
}

const findAddressByUserId = `-- name: FindAddressByUserId :one
SELECT id, user_id, street, city, state, zip_code, country, created_at, updated_at FROM addresses WHERE user_id = $1
`

func (q *Queries) FindAddressByUserId(ctx context.Context, userID int64) (Address, error) {
	row := q.db.QueryRow(ctx, findAddressByUserId, userID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCategoryById = `-- name: FindCategoryById :one
SELECT id, name, description, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) FindCategoryById(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryById, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrderById = `-- name: FindOrderById :one
SELECT
    o.id,
    o.customer_id,
    o.status,
    o.created_at,
    o.updated_at,
    oi.product_id,
    oi.quantity,
    oi.price_in_cents
FROM
    orders o
JOIN
    order_items oi ON o.id = oi.order_id
WHERE
    o.id = $1
`

type FindOrderByIdRow struct {
	ID           int64              `json:"id"`
	CustomerID   int64              `json:"customer_id"`
	Status       Status             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProductID    int64              `json:"product_id"`
	Quantity     int32              `json:"quantity"`
	PriceInCents int32              `json:"price_in_cents"`
}

func (q *Queries) FindOrderById(ctx context.Context, id int64) (FindOrderByIdRow, error) {
	row := q.db.QueryRow(ctx, findOrderById, id)
	var i FindOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductID,
		&i.Quantity,
		&i.PriceInCents,
	)
	return i, err
}

const findProductById = `-- name: FindProductById :one
SELECT
 id, name, price_in_cents, quantity, created_at
FROM
    products
WHERE
    id = $1
`

func (q *Queries) FindProductById(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, email, password_hash, created_at, role, updated_at FROM users WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, name, email, password_hash, created_at, role, updated_at FROM users WHERE id = $1
`

func (q *Queries) FindUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, token_hash, expires_at, created_at
`

type InsertRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS (SELECT 1 FROM revoked_tokens WHERE jti = $1)
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenRevoked, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT
    o.id,
    o.customer_id,
    o.status,
    o.created_at,
    o.updated_at,
    oi.product_id,
    oi.quantity,
    oi.price_in_cents
FROM
    orders o
JOIN
    order_items oi ON o.id = oi.order_id
`

type ListAllOrdersRow struct {
	ID           int64              `json:"id"`
	CustomerID   int64              `json:"customer_id"`
	Status       Status             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProductID    int64              `json:"product_id"`
	Quantity     int32              `json:"quantity"`
	PriceInCents int32              `json:"price_in_cents"`
}

func (q *Queries) ListAllOrders(ctx context.Context) ([]ListAllOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOrdersRow
	for rows.Next() {
		var i ListAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductID,
			&i.Quantity,
			&i.PriceInCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartItemsByUserId = `-- name: ListCartItemsByUserId :many
SELECT
    ci.id,
    ci.cart_id,
    ci.product_id,
    ci.quantity,
    p.name AS product_name,
    p.price_in_cents AS product_price_in_cents
FROM
    carts c
JOIN
    cart_items ci ON ci.cart_id = c.id
JOIN
    products p ON ci.product_id = p.id
WHERE
    c.user_id = $1
`

type ListCartItemsByUserIdRow struct {
	ID                  int64  `json:"id"`
	CartID              int64  `json:"cart_id"`
	ProductID           int64  `json:"product_id"`
	Quantity            int32  `json:"quantity"`
	ProductName         string `json:"product_name"`
	ProductPriceInCents int32  `json:"product_price_in_cents"`
}

func (q *Queries) ListCartItemsByUserId(ctx context.Context, userID int64) ([]ListCartItemsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, listCartItemsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsByUserIdRow
	for rows.Next() {
		var i ListCartItemsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.ProductName,
			&i.ProductPriceInCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, created_at, updated_at FROM categories
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomerID = `-- name: ListOrdersByCustomerID :many
SELECT
    o.id,
    o.customer_id,
    o.status,
    o.created_at,
    o.updated_at,
    oi.product_id,
    oi.quantity,
    oi.price_in_cents
FROM
    orders o
JOIN
    order_items oi ON o.id = oi.order_id
WHERE
    o.customer_id = $1
`

type ListOrdersByCustomerIDRow struct {
	ID           int64              `json:"id"`
	CustomerID   int64              `json:"customer_id"`
	Status       Status             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProductID    int64              `json:"product_id"`
	Quantity     int32              `json:"quantity"`
	PriceInCents int32              `json:"price_in_cents"`
}

func (q *Queries) ListOrdersByCustomerID(ctx context.Context, customerID int64) ([]ListOrdersByCustomerIDRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByCustomerIDRow
	for rows.Next() {
		var i ListOrdersByCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductID,
			&i.Quantity,
			&i.PriceInCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
 id, name, price_in_cents, quantity, created_at
FROM
    products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT
    p.id,
    p.name,
    p.price_in_cents,
    p.quantity,
    p.created_at
FROM
    products p
JOIN
    product_categories pc ON p.id = pc.product_id
WHERE
    pc.category_id = $1
`

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID int64) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeItemFromCart = `-- name: RemoveItemFromCart :one
DELETE FROM cart_items
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

func (q *Queries) RemoveItemFromCart(ctx context.Context, id int64) (CartItem, error) {
	row := q.db.QueryRow(ctx, removeItemFromCart, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeProductFromCategory = `-- name: RemoveProductFromCategory :exec
DELETE FROM product_categories
WHERE product_id = $1 AND category_id = $2
`

type RemoveProductFromCategoryParams struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) RemoveProductFromCategory(ctx context.Context, arg RemoveProductFromCategoryParams) error {
	_, err := q.db.Exec(ctx, removeProductFromCategory, arg.ProductID, arg.CategoryID)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
INSERT INTO revoked_tokens (jti, expired_at) VALUES ($1, $2)
`

type RevokeTokenParams struct {
	Jti       string             `json:"jti"`
	ExpiredAt pgtype.Timestamptz `json:"expired_at"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.Exec(ctx, revokeToken, arg.Jti, arg.ExpiredAt)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $2
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	ID       int64 `json:"id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, customer_id, created_at, status, updated_at
`

type UpdateOrderStatusParams struct {
	ID     int64  `json:"id"`
	Status Status `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, price_in_cents = $3
WHERE id = $1
RETURNING id, name, price_in_cents, quantity, created_at
`

type UpdateProductParams struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	PriceInCents int32  `json:"price_in_cents"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct, arg.ID, arg.Name, arg.PriceInCents)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, email = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, email, password_hash, created_at, role, updated_at
`

type UpdateUserParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, email, password_hash, created_at, role, updated_at
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.UpdatedAt,
	)
	return i, err
}
